# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 4) do

  create_table "events", :force => true do |t|
    t.column "date", :date
    t.column "from", :time
    t.column "to",   :time
  end

  create_table "resource_uses", :force => true do |t|
    t.column "event_id",    :integer
    t.column "resource_id", :integer
    t.column "collision",   :boolean
  end

  create_table "resources", :force => true do |t|
    t.column "name", :string
  end

end
